name: v1-core

plugins:
  - name: solidity
    version: 0.6.3
  - name: foundry
    version: 0.6.7

default_ecosystem: ethereum

dependencies:
  - name: openzeppelin
    github: OpenZeppelin/openzeppelin-contracts
    version: 4.8.3

solidity:
  import_remapping:
    - "@openzeppelin/contracts=openzeppelin/v4.8.3"
