name: v1-core

plugins:
  - name: alchemy
    version: 0.6.3
  - name: etherscan
    version: 0.6.11
  - name: solidity
    version: 0.6.9
  - name: foundry
    version: 0.6.12
  - name: arbitrum
    version: 0.6.1
  - name: base
    version: 0.6.3

default_ecosystem: ethereum

ethereum:
  default_network: local
  local:
    default_provider: foundry

foundry:
  base_fee: 100000000000  # 100 gwei
  priority_fee: 10000000  # 0.01 gwei
  fork:
    ethereum:
      mainnet:
        upstream_provider: alchemy

dependencies:
  - name: openzeppelin
    github: OpenZeppelin/openzeppelin-contracts
    version: 4.8.3
  - name: uniswap-v3-core
    github: Uniswap/v3-core
    ref: 0.8

solidity:
  via_ir: true
  import_remapping:
    - "@openzeppelin/contracts=openzeppelin/v4.8.3"
    - "@uniswap/v3-core/contracts=uniswap-v3-core/v0.8"
