name: Unit Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ApeWorX/github-action@v2.0
        with:
          python-version: '3.10'
          ape-version-pin: "==0.6.12"
          ape-plugins-list: 'solidity foundry==0.6.12'

      - name: Compile contracts
        run: ape compile --force --size

      - name: Output current installation
        run: pip freeze

      - name: Install foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run tests
        run: ape test -s -m "not fuzzing and not integration" --coverage
        timeout-minutes: 15

      # TODO: uncomment in separate workflow when fuzz node issues fixed
      # - name: Run fuzz tests
      #   run: ape test -s -m "fuzzing"
      #   timeout-minutes: 15
